-- ** Tabela: CLIENTES **
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID SERIAL PRIMARY KEY,             
    NOME VARCHAR(255) NOT NULL,        
    CNPJ VARCHAR(18) UNIQUE,           
    DATACADASTRO DATE NOT NULL DEFAULT CURRENT_DATE,
    LIMITECREDITO NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    REMOVIDO BOOLEAN NOT NULL DEFAULT FALSE
);

-- ** Tabela: CONTAS_RECEBER **
CREATE TABLE IF NOT EXISTS CONTAS_RECEBER (
    ID SERIAL PRIMARY KEY,             
    DESCRICAO VARCHAR(255) NOT NULL,   
    VALOR NUMERIC(10, 2) NOT NULL,     
    DATAVENCIMENTO DATE NOT NULL,      
    REMOVIDO BOOLEAN NOT NULL DEFAULT FALSE,
    ID_CLIENTE INTEGER NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID) ON DELETE RESTRICT
);

-- ** Tabela: USUARIOS **
CREATE TABLE IF NOT EXISTS USUARIOS (
    usuarioid SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    removido BOOLEAN NOT NULL DEFAULT FALSE -- Corrigido
);
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- Habilita a extensão pgcrypto

-- ** Índices **
CREATE INDEX IF NOT EXISTS IDX_CLIENTES_NOME ON CLIENTES (NOME);
CREATE INDEX IF NOT EXISTS IDX_CONTAS_RECEBER_IDCLIENTE ON CONTAS_RECEBER (ID_CLIENTE);
CREATE INDEX IF NOT EXISTS IDX_CONTAS_RECEBER_DATAVENCIMENTO ON CONTAS_RECEBER (DATAVENCIMENTO);

-- ** Dados de Teste **
INSERT INTO CLIENTES (NOME, CNPJ, DATACADASTRO, LIMITECREDITO) VALUES
('Empresa Exemplo Ltda', '11.222.333/0001-44', '2023-01-10', 10000.00),
('Comércio do João S.A.', '44.555.666/0001-77', '2023-03-22', 5000.00)
ON CONFLICT (CNPJ) DO NOTHING; 

INSERT INTO CONTAS_RECEBER (DESCRICAO, VALOR, DATAVENCIMENTO, ID_CLIENTE) VALUES
('Venda NF 001/2024', 1250.75, '2024-05-30', (SELECT ID FROM CLIENTES WHERE CNPJ = '11.222.333/0001-44')),
('Serviço de Consultoria', 500.00, '2024-06-15', (SELECT ID FROM CLIENTES WHERE CNPJ = '11.222.333/0001-44')),
('Venda de Produtos Diversos', 320.00, '2024-06-01', (SELECT ID FROM CLIENTES WHERE CNPJ = '44.555.666/0001-77'))
ON CONFLICT DO NOTHING; 

-- Usuários de teste (com senha criptografada)
INSERT INTO usuarios (username, password) VALUES
('admin', crypt('admin', gen_salt('bf')))
ON CONFLICT (username) DO NOTHING;

INSERT INTO usuarios (username, password) VALUES
('qwe', crypt('qwe', gen_salt('bf')))
ON CONFLICT (username) DO NOTHING;